def builder(data: dict, location):
    location.write("<!DOCTYPE html>\n")
    location.write(f"<html>\n")
    location.write(f"<head></head>\n")
    location.write(f"<body>\n")
    location.write(f"<h1>{data['name']}</h1>\n")
    location.write(f"<p>{' '.join(data['types'])}</p>\n")
    location.write(f"<h2>Stats</h2>\n")
    location.write(f"<table>\n")
    for key in ["hp", "attack", "defense", "special attack", "special defense", "speed"]:
        location.write(f"<tr>\n")
        location.write(f'<th scope="row">{key}</th>\n')
        location.write(f'<td>{data["stats"][key]}</td>\n')
        location.write(f'<td style="width:255px">\n')
        location.write(f'<div style="background-color:black;height:20px;width:calc(100%*{data["stats"][key]}/255)"></div>\n')
        location.write(f'</td>\n')
        location.write(f"</tr>\n")
    location.write(f"</table>\n")
    location.write(f"</body>\n")
    location.write(f"</html>\n")
